# Generated by Django 5.2.1 on 2025-05-31 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tagtrack', '0001_initial'), ('tagtrack', '0002_album'), ('tagtrack', '0003_alter_album_artist_song'), ('tagtrack', '0004_alter_song_options_song_retag'), ('tagtrack', '0005_alter_song_year'), ('tagtrack', '0006_alter_song_number')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='albums')),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='tagtrack.artist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('artist_id', 'name'), name='unique_artist_album')],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='songs')),
                ('duration', models.PositiveSmallIntegerField(help_text='in seconds', validators=[django.core.validators.MinValueValidator(1)])),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, help_text='Song position in album', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='release year')),
                ('image', models.ImageField(blank=True, help_text='Use only for singles', null=True, upload_to='singles')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='tagtrack.album')),
                ('artists', models.ManyToManyField(related_name='songs', to='tagtrack.artist')),
                ('retag', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['album_id', 'number'],
            },
        ),
    ]
