# Generated by Django 5.2.1 on 2025-05-13 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagtrack', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='tagtrack.artist'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='songs')),
                ('duration', models.PositiveSmallIntegerField(help_text='in seconds', validators=[django.core.validators.MinValueValidator(1)])),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(default=1, help_text='Song position in album', validators=[django.core.validators.MinValueValidator(1)])),
                ('year', models.IntegerField(default=1, verbose_name='release year')),
                ('image', models.ImageField(blank=True, help_text='Use only for singles', null=True, upload_to='singles')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='tagtrack.album')),
                ('artists', models.ManyToManyField(related_name='songs', to='tagtrack.artist')),
            ],
        ),
    ]
