# Generated by Django 5.2.1 on 2025-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagtrack', '0003_alter_album_artist_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['album_id', 'number']},
        ),
        migrations.AddField(
            model_name='song',
            name='retag',
            field=models.BooleanField(default=False),
        ),
    ]
