# Generated by Django 5.2.1 on 2025-05-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagtrack', '0004_alter_song_options_song_retag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='release year'),
        ),
    ]
