# Generated by Django 5.2.1 on 2025-05-31 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagtrack', '0005_alter_song_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='number',
            field=models.IntegerField(blank=True, help_text='Song position in album', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
